<?php
if (!defined('BASEPATH'))
	exit ('No direct script access allowed');

function get_config_val($key) {
	$CI = & get_instance();
	return $CI->config_model->get_value($key);
}

function get_confirmation_process(){
	$param = get_config_val('payment_confirmation_process_'.current_lang());
	
	$tags = array(
		'[PAYMENT_CONFIRMATION_EMAIL]',
		'[BANK_NAME]',
		'[BANK_ACC_NUMBER]',
		'[BANK_ACC_OWNER]',
		'[MONEY_ORDER_RECIPIENT]',
		'[MONEY_ORDER_IDENTIFICATION]'
	);
	
	$data = array(
		get_config_val('payment_confirmation_email'),
		get_config_val('bank_name'),
		get_config_val('bank_account_number'),
		get_config_val('bank_account_name'),
		get_config_val('money_order_name'),
    	get_config_val('money_order_identification')
	);
	
	return str_replace($tags, $data, $param);
}

function ci_config($key) {
	$CI = & get_instance();
	return $CI->config->item($key);
}

function get_hash() {
	$uniq = uniqid('', TRUE);
	return md5($uniq);
}

function current_lang(){
	$CI = & get_instance();
	return $CI->lang->lang();
	
}

function logo_svg($w=73, $h=95){
	?>
<svg 
     version="1.1" 
     xmlns="http://www.w3.org/2000/svg" 
     xmlns:xlink="http://www.w3.org/1999/xlink" 
     width="<?=$w?>px" height="<?=$h?>px" 
     viewBox="0 0 73 95" preserveAspectRatio="none"> 
   <g> 
<image width="73" height="95" xlink:href="data:image/png;base64, 
iVBORw0KGgoAAAANSUhEUgAAAEkAAABfCAYAAACk/OpaAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A
/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB90GBBYWMTe7rYkAAAAdaVRYdENv
bW1lbnQAAAAAAENyZWF0ZWQgd2l0aCBHSU1QZC5lBwAAIABJREFUeNrtnHmUXFd95z9vrfde7V29
t7ql1mJkWauFsY3xgg0WMRhwxkAO2ZjEC0tyCMlwJjOZSTxMziyZmZAVMCEhAwyQsDgYYmNs4QVb
2LIWS5ZlSVa3pG713l1VXfvb6s4fr+p1Vy+ymEli+Rzfc+q8V2+5777v/f6W+7u/+yQu4RIxjHvO
njlzv+d5AFQqFY4fP061WiOTybB9+zZ6enqk/5+61w0O3mvXal+80LXSpQLI6Oio2Lv3x7zyyitU
azUURQUgHouSae/A9TyOHT3K9MQYrgia3dfbyy/+0i/y9ptubHmPF154QUxNTZMvlMnncwBUqxU0
VSWdSmKaBqeHzpDPZYknEnR3dbFnz62rAi69liz51jf//v7nnt/Pvmee5uCJk9j5HG3pNvp6e8i0
ZVizZg19A2tRFZnDhw8zOz3F4Lp1bNu1m3wuy9Arp7Bdj4/82l287/bbpL/83BfEF/7yzzk1NBQ8
I5VmbaaN3t4+1qxZw6aNG0h39jA7M41t26iKDIDn14nH4/z8He9jw4YNyzBRXguA9u3bJwq53O1/
8bnPsffHexk9fx6/VgPANE0S8TixRIp4LIqsKBw78gJjY2NMT0wxMTVJPJXm7TffQrqtjZnJcYaG
hrnyyt33/fWX/oqZSjWsy6/VyLS1EY8nSCQSmLEExUKBkTPDnDz1Cjt37qKjvR3P93Ech/Nj4+zd
+9iE73kHF7dX/pcG6PEnnhQf/9jH2f/s/rC3Vyu+73NmeJhUKsXdH/0EABPFEt/8hwf4x3/8AWv6
B9i2azeeYzM9MbacrUvqrlarlEpF9u9/jmcOHeTbf//Nhtj2oCgylUqFr3z1G/cvrednBmn4yOPi
0GPfEM/+4Evi0GPfEIce+4YYPvK4iBjGPRejdz5z3x9QrZTDY3ZDZ6xU5otFZqen+Fe/8Ivce/ev
Se//wJ0ARCWJxx56iFMnT7BxwyBdvX10dHaxdqC/pb7F+77v4/see269lTVrBwE4eOIk3/ve9wBI
t7XjOA4TE2MMDQ2Jxe1QLwaYF/c9KJ544CtMTJzmS//jU+HxvkQk3P/yp26+31i74/5N269l21vf
u6Ku++yf/CmzMzMtx9rSbWRz2RWfm89l2bH7Kt53+20SwKd+65M8+sOHmc3mmHVsHnvkhwzc8zHW
b9hIqTDPurVrOTcyGta3mEmKorBhw0b27LlVevAfHhQvfOyjABw5eIgtW7awadMmdF0H4MChoxfP
pBf3PSj+/NN3ij/+zCc49OJzAd1n58LzYwU73M/Nz1E7d4QXv/8FvvVHd4kX9z0olorZU088vuwZ
qwFUdx10TeeWt98YHuvv75fe9e7bKQtBVJI4euwYJ18+Rnd3N7FEkvbuXtrb0isyyUym2bVzOwAf
+IUP3rt961bKQlB1HQ7s34/t+miKgu95zM5MMTU1lX1VkL77hX/XAk4ToJ72zDIWLQYqNz+Hmxvn
xe9/gYe//tkQqAcfeGDF57Sl21btpK7ODq655pqWY++45Wba9YVn//TZoH09vb1oEqEoNZnkOA5W
LMaani4GB4Nzdq32xeuuv56oJFEWgrNnzzB2fhQtEsF1HVRN5/jLJ9IXFLc///Sd4vv/8LWWYz3t
GWSzg65Uku6OVHAs0RHIeyEQITc3HgKVTmYYfvqbPPm53xDxy67jd/7w/hWBWI1JABvftBlZlnMT
ExMCQJblXKlUYsfuK9n7059CWw8nzk9yfnSEzvYMM1OT9PX2tjBJz7TRlkox0N8f6kVVVTlx8hSf
//zniUoShVKZs6dP0dXVhe/XA0KMj6+uk771R3eJh378SMuxvv7NrX5DogMz0UnUjKBrOrqxfUFM
ZoaYPf04QxMBUMeOPc9zz+SoVqsr+0updKtYaDqqqiJrOtu2bcVxnLTjOIF18tV0Jm6xZtu1cPIs
GVVmzqszMjLCmv63YUVjJJI11vX3c3Z0NGirqpFsayOTyVCpVHAcD1mGjvYMG9cPcnr4DACnTp9m
267dKIpMtVohoikr66SHv/7ZZQD1tGcYGz3B2OiJAOGJ0xx4+mFOH36G2alRcoUiTi2wVpoVpW3L
dfTd8kmuvv52cvNzPDduMTU9g6ZelI2g6jqYpklHOkkq3cZ8tU6+7JEve9i1GnNFh/WXXQHAjNUN
wP6zM9RqNtFYjFgsTm9fX1hfPBYlk2lHj0QoFotUykVKxSKe53H5th2URaARpiemQqvrNjrl5MmT
ooVJQ0ND4g8/cdOyRjf10K984JfpWjvImVmboUN7OXz0ABMTp9m1/c2w5gqiroNeK+NWyqQ6upmI
9vHVg+B5BeLx+KqgLHUBTE1H13Tau3vQrRTz+XzL+VqtxprubuqJXuTCOPVEL8+fneBut0YqEaeQ
z9HV2RleH0umicZi4dgPwHZcErEo6/v7wmdWXYfz4xOsHRjA9x10XWdubq5V3A5957+u+iI//+47
GdxxOQBXpAy2bruLd0zcxuPPPs+Bpx9GfuUcOzatpWvTlQD8zVe+zp/9nx9g53Ps2rHjwsOTJeIG
IGs6qWQSgPGCT29CWbZdt/lyzp5YuGd6do6enuCle3oW9FJXewbTtAJrXDFI+LMAFAAjnqRdj1B1
A+bMTE2yfnAdjm3jOA7FYmkBpNHRUfH7d791xZfoac/Q1TtAJV+jGttARg0822hPL++5432s27id
oUN7mT77IoePHuDgVCdP/OSp8H5NVdE1Hc91L4pJ0XgUI6ITjcUZL/ghUM2tE48yXigzMLCZMzOl
8L6h2Spr+0GPREhnMqH/FWv4SrNeHL06Sa3JSMfDNC3aOjKMjU+EfllzLAeETJIBjv3k2xfs7Vgy
hpUyQoBCrZ/oZ+d1N/DeD/48E+Z2vvNcmZ+++GLrNZoWyHkj3KGo2gWHDoqqkYzHMQwDgLOe1LId
zwUiE8ukqFnt4e/0VCCWmhYAnIhFiaTSJM0IEU3hrCdRq9kMz8PwPNRqNhWzmxkrFj67WCxSqVTx
PRfb9VE0YwGk04efWRUg2exYcB7nTSQz8GvOT1Z56fBBHnv0R/zuZ3/Etx58AqDFh1nsAzUVt++5
F+yQeCyKqkdwEgPLANp//ASfv+cOnnpqL8mOoF31ZBf1ZBejtoMiKSiqiqKqpNvaiEoSimGRUztQ
ZycYtxfa9rdf/muKwwf5rXv/LUZHL+V0N57nY9t2yCRTU5iamsqqAFP5+VUbvWPTWqyUQSVfoy8F
olrlG0/M8Pz+/czNzvDC8CFSSgbTilKtlEP5bvpAuqYvZ5LjrCpuqqYhqyqTjkH7krYc+O4XGZue
pDL6Mr/+kV8B4Es/PrrIMvqkEnHmsjnSmQ5y2SyWvtyqjmfzvHD4EB+75x7Wb7mCH127h2d+8jDz
QqVcqRBVFTzXQSgqjuOk5aGhIVGvzqzoD9128x6uufoGKvkaOSkQiyePTrHv2edw64LDhw8TE0k0
VQ0ZkohF+fBNHXz4pg4+9K5rkTUdx3VWZdJSj9uwYlhq4JlMlGrh79mRGfY9+yxt6TZuve12El6N
D7xlE+u7g3ZNJjZSLRcCdtXrJGMWphVFiZhMOkbLrzY7RjaXpVQpY9dq1Oanw+cLz8WVWoeeqikC
5Xf7+3+JN2/o57nDh3jox49w5baruebqG4glA5lNixxg8NzzQ+iGyez4KIVSmd6+PqrVKqlUiusH
y2zt72XOs8ioFeY8i0ePV0NleTEetyYJPDVCBCg6AaBxXaN6fjTsBFNTsGs1tKRJW8zgnLag53Rd
R9N1Mu0d+C+9hCwHgGcNlbZawOam/vqzP/0TrtpzJ8+fnUBe5HdpQoTuQqVSQa1KAQibMnEqlSrb
3nQ5kzN53nfrzQCU5kshUC+dnqfk1klGTV6ansZsiFIykeQ9OxNk1KDi5vaiIpSLXIBIKo0VjQaO
HIKmNpzTJMTUcCC2tktpUagl7/nIhga+S75QpLM907CoWmgk6qVJsl47WcBXlZA5h48c4ZjU0G0N
v6tW7SRimgssUlXk9oRBT89GbK+O69igGiFAS4tTKxOJRLCiMXK5PFokaMRV6wSbEsGLauletHQv
bVYQIWjGoy+m2PkcetMaCkG2VGO86pAvO4zagR4bm57kf3/5y5w+eZy/fWGYc3OlZcZB1XSkxr6i
qpwTEYr1Ok5DIc8YqQXxyvQjMv0hUON6D3U74L6hq3ieh5zs6JOaA9bASahRcQJXXTilkE0AjusQ
iURC8wwQj0bZ0q5RjAyipXuJ28FYyMxcHoY8Xg2YldyBiu1SrNcRnk+5alMc2h+ee+InT3H3H/xn
vn3wNIqpo5g6dU0PjUMQP1pQ2LpbxnM8slWbQmn5GLJmtYdA9ToTC8cdL2ASQP+Wa6g7lQU2rQKU
rulETRPDMDCMwJzqmo6W7qUzZoTgNPe7O1LIDZG8kLgtBkxuvNx0zcatC6p+nXy9zpzbOrSxh49T
90C1NGQVlEjrc5q6CCBbcJnyPBzHw/b8Fid0cRGZfiRFxa2LkEmhnzSw+aqg151KY4C3MlC9EQct
EiFqmaxbu5ZCqcxlsTMhKCFQ0QRmNBEq4p+FSYqyMPqertlM1+xXBVfWtRZxi2hKOBPSHJI4FYe8
55NneXvqyS5qVuBwCN/Ddlwsy0KPRNB1PQCpd+MOSdaDymyvvipQkh5jfaqKruts23nlMmdzMTim
FUNJdLyqTlrKJK1pjZosAEqut+K9qqUh6yryCr6QomqB31YqBi4CgnrNxak4WF2ZFlFTFllHTdMQ
vtequEN/Zct1C41dClSlSsURCKfEYDQ4t3XbdnbuunIZOLJuYVoxtIbn/WpMWgqYWw/qL1XsEKhp
3w91xoKD1YPZETxTUmRSVvCijhOM4FVFxrVdtLrXkBKXSVmQr7hki1ILi5pbqysDvo+kqEQtE8e2
WTc4eG8I0vodb5dMK0bdqRBLpNGs5AJQSxT6ZdIQevEk77nl7XSlki3gRFQZTY9gWSYDyWho0lcb
uy2d3XAdG1PX8CouFc+n4vmoutbS+y2MMbVF3vqCXprO5hmbngzwTGjUPah7UEIgta8JO0WLWwvG
YmoOVVNQZQld16k5Hnat9sWWoNvATb8avFBlnkqkDc1Khsq8ySqAiCrTIZW5urfK1VsvQ9atEBzN
SmJZJpIeI5ZIYxgmnutetMftuC41I4PhzqGYGpKychjeH7waralYdQVNzIXRREUzEE6rC+tXHeSG
VGrpKOot/5ry9Xe1XPOWuIfn+iiqimkaK0cmkx190prrPkR2ZhyrPE40FieWSGN79RawmuJYdypU
y4UAoAY40VgcSQ+cz66+HmKWcUERW+pxe45LWqosUsrBi1fWbF5mtjVdwYyZqLrGOldH13XKlSqp
RJTxicCUj4yN06OraHEdWddCoOo7rkNZszBp0NRLNddF1zQsK0pHJrXybEnvxh3SplvvplSpciZb
CoECqFZKLQCFyk6P4Fbmmc/nKednwvAKQFdHx0UrboBiuYyqyPQkdFRdQ9U1NF2l84o1RNZvCa/r
vu0GrKSJbmlYsQhtCY1mLFyPRJidngrGf1OTXJFw6W3MqS0GSjEbxwwN33XpV4J30k2LeDxGpHnP
Sg3v7mtnw+VbEBPHmTh7gkqkja7eARKpTAtA56uBjqod+yravs+i7fssPPHfmHv6jynOTGKlDN58
eQZV0y5KJwHMF4KIxFqcRgeo6JaGGY3Q9eHfDcZvH/439KzvRItoJNpiWElzmV6ang6GHqNjYyST
CTQx1+pHLTGI8vwUsqJS9z16enspFkuk0unlsyWjT35FGKcf4NS/34kVNxgEKsUabuEtTCR2kGjv
Q+7oJWZncSvzZMrjdL3yd8tANmbHqDz0B0y//39ROv9S6MN4nreiTloscp7nIbk26AFAViKClQiU
a/KWK7CufhorZqJGVDRbRY2oFOaK7JKz2G6CiKaQz2UplILxXS6XZ36+wJVmlLG6St3xkHWNutPa
jsujNag3orGNMHAzw0QFcLIjYv6BT1Ld+3tIa9K037gwTNFGZNyZo2jD+znbtr1lyDE4+T0qgBUP
9E6l2KosX/7a7zA1VUHXrls1fLtUJ2Vn5hBahI2uw8u6gpWw0Boip0ZUOmMpVCNgo6e5qIZG7OQk
hmHguQ7d3QOcOTMc1lutlJkcO8/utbv43tkish4AFbLJ1HFzZTpqedChLZ2ms6ONQrHcOu82/8An
8cqHsK40gNaxjTagoxkmnM+xLnuUkRLYI0cZiAFxY1WAWvSc8jKnGbioiYCq65Cfn6evM0KnpqI0
WGNoCqqhYVqLZo4b+13MhG5GIh7l3NDpFn139twIP7d9F/0iy7jSHeqmJpvS9ij9SoVazaVvezBx
sWFwob1y7oXvCm/mGNrABcZYnVW0dplkV4qBGAzEFtjzz1HGR0eCnCJ7bkWAepNqyzb0+BtDkLMj
IwtRBV3nzJkz1D2bdyeTgSuwxEPfWgn0kWGYbNwwSKFYZuvWraHHKXsHv4q2+QItnjZh2kQzkmA5
WIvYo1kXB9RuPRtOCLzabAnA1PQ0qqbTPVXE0BTibbFVAeorOawfG2lEJEwKxTJHDh5qYZLjOpw8
fpy3DaborHktY77Y5IkGi6oMDK6nq6uLRDy6PKtEyyeXNVTLJwOAGsWtzUNFR7OM8OdWFkRsJWZl
S364v84YuigXoDlrkZue4Fprwc3oTarLmAMghqfRGoPiaDzJ5ORk6Gk3O0DXdE6fORfMIXZKDeWt
Ys+VW1i0a+d2isUS73rXnntbQBKFk8vAWQaaW0dTglCFElk0GGyAdSGgFrPJNIyLYpLn+YyOjRO1
TNrPzq1Y36CmEik5bHzlWbRIwLKOTIrHH/3hih3gOTanTp7gHW9q521iEnnmPNdN/JS1ukOtVuXa
62+kq6uLeDzG0mxcWdblFcFxHQet4UyhySFAsi6jRLQWsBaXJlAjK4RsNsZHXnXeLdRLExPYrs9b
5ueWgTOoBYyyDr8QTn23d3RRLJY4cfJUSwc0HUxFUSgWi8zNzfHRnZv4uD7DetNHURSuv+lmtl2x
Gdtxeetb37osbKEKYxMwulzcGgCFQOngag64dZrAgoZvuyGbmuJnxQ0oBfvt0aCXZ8s2u/Us9MC+
oQvrMlVVqJRKTE2MMTCg0D+Wx08G8Z4zrsegpjKeq3DZ+UmqgGEYdHa04dg23//B9zlw4ABP7t1L
NpejWKkS0RbGjcVylUwmwzve+U4c20ZvsLBYLLFnz60rxnVUANWI4NVsVKM1Mat5zGsEvjRdx214
wgtgBUCtmKAVU0K91ARrN1leTGwOp5ZXy5mUNZ2RkVHedPlW1p0a5vxAAjumt7KoMgVSnPaOINyx
bt1a+vv7W140Yhj3HH/ppfur1Sp2rUahVMaxbYr5eSKmgWPbtGfa2L0kF3xxkQoP3y2U+eMXZaW8
RVFC1wlYFQxTgq1vu7iVWovPNFJqVeCz5aCOr01tbclvXOyB9/X20NHVQ1d7hvUbN7Jt21YOGRFy
17+FSMnBOvwC3WdGcD2PVCLO2nXrAJYlvf9TFeVjH7nrvrQ2jBrR8W2XSCLasr+YJbKqIqsqdS+Q
5Tp1qAskRUL4AuHXUTQVu1zDihtoERULDwcZU5epOgJLV7F0lY36BNGOKF49Sl02qNaqDV/HxDIt
4okEyXgcRdOJmFG2p1L4h0YpHTjBurmT2EILAXJsm3e845Z/tsR9Nd7RDeMgpwbwJQlEYCojiWi4
tQvlcLtYPEPxazBKiWjUcsUAoIaesgBJiSHmZ1vEr2nxdm+Gg04bV257D/ErbufAocPUKhWE76FE
DHRJUC0VqVTKbOmIsi5qUq2uozueJBGP4tj2qrrknwykaE8vjAPRXmKMAwPU8yOtFigRbdm3C+Vl
QMkNsdMsI7R8si6jxSN05FVmGjP7bcySLfm0RyOh6O3Ws9w4UGXbR35VWqxLjh45cn+pWGR2Lkul
UqZSKeN4YJoGhq7+iwAEjbUlhYfvFrHeHiSrA1Fp5FmXx5eBFZrWBqNadFS5FuomOaq2WEapVGV4
XmMmF1wv5gOgmiABbLzqGt71H/deMguCllm3WG8PlMdxktegWwRARXvDYNNqYC22fCED0lZ4biF2
EmGNXgQizORspGQ7bcwCC2wamijhZEeE3jZwyQElAxR776WeH0F3h3ATVyFZHUhWB0SDtDo5NbBM
/JoiuBiMSNpCNSJEO9vCa5q/1Jpg9N2RDq6XGn5P0zXI5F7hUi1qM7ZdePhuEQfQenG0DYH/aAEN
EVzKqsXKXCpV0QGnXGOaFLUZDSO+wLBeI7Bcg30qZ8Y8OtIBoxYr8rn0pksbJIDI5Xcgxr8LiauQ
ElvBHccBdHco0FUNPSWnAsUeSUQpT2f52n6FA8MFfGNjc14CqODoHRiGiaFptKcCCeqSA8dRLo9y
mdUqppvcYaq+ckmC1CL/9SO/35hYCwbBXiEYrohqFt0dCnRVQ6EfOzzNn/5kjifGA283owlMw0DV
NIxGHmIyZqFrGrKioltRdMPEafhDmiyRdk/RoxXI5F4h09fFO//ny9IlzSQAr/8u1BOfwZ06gta1
AzXRj1cYbQFo6NRZ/ss3T/LkcYWq65OIzQerezQD1/NQNY266yBrOnZjeloHfLuGkAMM6p6Hq6pM
K5vI131I7uSt2ijwMpc8SHrbgGSffUjYLz+A7gbxH3XmCH5+hMcO+vzdM6f4zgteuAzU1HTchkfe
HN03l0fosCzDTVICj134HnVAlSUcWUGTJc7EbwAeuvRBgiDD9sP3HeXmTc8jmx08f1biXG6Y8fNl
7HwuDG2UhYCW3KMyuq7jLQqFLAVKVuzwgcL3cH2QFIG7KOfydQHSuZzM4SNHOH4uDW0Nm5Ytrxr7
MTWdRDqFYUTQVBXX8yiXSqsAVcVoxHZcx0ZWVBTCmZzXD0jF/PxyMNp6IDuxLKLY3tlNW0eG3u5u
Ojq7MEyTiGkyn81y6tTJFtHzJYHdBMoIwsL1RoqLwkIW/usCJF/4gVgtmlJeCtCyYYrjUi6XMEyT
WCzOwNp1GKbJM88807I6KQLYgK55OI15OH0RWJdqWTbNPT27QhCsrWfFm6uug12r4bgOthtkiPm1
Cq7j0NXdHUQCS2U81w2ucVx8x6ZYWZjbc1w3BOx1w6Tc9AJr0pk4ubniqjeXhSDhOOHsrPA9qp5P
ChgZGQ3iy44T5lcuZVT4X1NfX0yanJgIddKFAGqZTPE8fMfG931EIzFi6PQpCqXA4tVqNtVarYVR
AH4jQcx2vdeXdZtsZGOkM/GLAsq1XTwvELW67+EKmJ2dDZe2N9lkWtGWFGLZdgAJ13YwIvolrbiX
MWm+tDAh2ALQIr3UZFpUksKE96Z+0SSYnZpkNpujLETobPpeAGa18YmMWqXUkuNdr7+OQDp/7gzR
xgKUeqKXXquwzMKtNMPhNF7YFTA+Nb2Q1eE6uLaL4wRK3vN8qtVqKHo/S+LpJQHS1NRU1nEcyunu
xqC1yHglsSqTlrkCrke1WOD8uTMtYC4GqsmoMKlLjzT0mff6ACmfz6cLpTKZxlKq3Fwx1E3R3OQF
KwrXtTl2+Gmepe5CEyjP86nVbDzXDS2b475OQBqfmMTUdOYaeZHpTByzGiwpLae7W1ZFrsSmiKYy
k2tdYJjNZVtED4LEqsXWTNEjJOOx1wdI0zPZFssGhOLWaxWYdewV9ZK6yKuembqwd14olUNlrmoa
uqZRKZWIJxKvD5BmZ6aWXdBU3OOVRMikqCSFTGp+KSYQOS2cvl5asrls+KGCJqN0TUdWVBzXCT9/
ccmDVMzNtZh0gKrZWGvvFpmNtYUfQYlKy4OI+Xw+BGJFxb7C+n9FUahWq5wbGXl9gDQ6No5jtuYm
yfNleq0CE1qc9lI2ZNJSMGRNp1guX/CjUU1GAUQMA00SKJHGsvK6zyOP/Ehc8iDZjkvMb00srSej
2E4qtHgrMUVTVTRJUCwWL/rBnufjCilclKwa5utjWDI3N4tr2qzvu4zhsYVkqIieD3RSg0WmpmMS
LPU0NZ1oLIYrJLIzcxf10KbFm5qepjSfY3piCrV+6boAoWIZHR0Vd/3ar3NqKks92ZpYmcjOUlJM
6sko0Vt/geSOzfRHU8i1YeYPnSf3g6/jeR6nxsZfVdxC92GRcxrNTbJz15Vce83VDAwM8JFFOQGX
FEjHjh0Tv/kbv8FE6Tzq1jvon36Z4w3xmU1sQd+yGW3jZQxs7mVgYxfXtS9kq43nKhz/q2/xwuf+
+6ofjYqk0tTX7aa263aig+1YqkLS0CiaOn3RCOXzWaSjz9BRy7Pe9Ln+xhsvGbDCRuzbt098/GMf
J5dIMpsIopLNNWa19dvQkiadikJ6jcXmRIa2ze30pi02VAKdMmTV+fYjh5n8D59m/NSxFsb4g1dj
D+xES0eRVUikYvTFTdJWBD1t0WkZxHqCVQgHskXmH3uKrr1/x46tW/mTv/iL1xyocMr0gx/80H2P
PfooY3IHWEkqPVfgJjqxjTSyKiHJMlVFYr4qmJbqzPkSlg2iQyenCTZUZHo62zi0YTe1Fw6iCg9/
9/spb9kDveuQVAXh+UiKgofAFgLb9zF9MGSJmKqwUdPY3J2k+82XcWZgK89/9+9555VX3nf8xIn/
dElYt4mJCVRVQS6MI82NIs9PUa8FnnHdA69Uxa+6OKUa87NlZsfneGpkmpEjkzDnMDKRZ0PR5bb+
Tvw7fzugaaMet1gJ6/KrDnXHpZAvMZYtcXAiyyNnpzg1lqNeqKLla1wfiXHnm6+g99P38fxcljvf
f4c4eOCAeM1Bmpldbpl816Vec4MX86DueAi/HgI1MTzD914ZZ+R8oIdGfJ+rTIMbdm2gfP1dyGcP
rvjQpYbMr7o8d36GR7PzzE7lGZnI0zVX4c1v2kDsjk9xcHiUA4ePvvbitvXyy+975dQpVFWnosXQ
CpP4kTiSlQhFRVYlQEKSJeqej+941Erv1fizAAACyElEQVQ2VSHYakSQIhqmEGxvi7PPkXFfPoQ+
8wqqquO5Hr4UoRk+qjs+IDXCvRIIGJ0rcS5f5vmz0/zjzDy18zkmDY25sQLloz9haHjoNRE7dUHc
xikpJlJ+FtmrU0/0YlRmqc2Cm+xC0TQCgXFQTB1ZXVjp83LV4WvzVeJuHSluEG8sYyhf8W46n/5r
2qWnUFSNeaFSmxlf0SEVbT0IgszEZjm6qCfPusXX1rqdPHlSfPTee0OPWW0s4AOYc6XQb5pz42S0
Ysv+nBunozLJXAPYFlkujHNtXzuf+8LnA3htJ4yht0Q1bZuJxgqAiKag63q4dH16kRq46Ya3sXPn
Tuk1YZJlWdz2nvciyzJnRkah7ofLDeS6T6VcwnFdPMcF2haFbGOAgExXY1iz5Lsk8XZ+7vb3rviN
6zfKG+Xii2iU1/t7yCu9VKPUhBAvCiHe/0Z3r9LzQojtjb9zbzBp9dKMp86u9MJLAP0tIcSoEMJf
DRghxJ1CCFsI8X0hREQIsV4I8bAQotz4/VAIMdi4dtVzK9TbJ4T4lhAit6RNF6pfrCA1Rxrv4Akh
poUQd1+w5xcVWwixZ9E5bxWQqkKIkhBi3Sr13dUA8NtCCK1x7tnGuT1CiJ9r7D/7audWaPPTjfO/
KYTQFx2/UP3N8gEhxGWL/n9QCLGxsV+4GHG7vPF3aClIQghlybVfaYCwTwjxpBDid5c0pi6EOCWE
UBc9y22c0xvMEkII59XOrdBmp3HeWnL8QvU3i3Kh/z8LSLnG/2Lj/4ZGDywVvx4hxC8v1mOLHv7b
je3fLGrIc41j72z0thBCPHcR55Y+95nGoU80Wfr/UMcF/19I3HwhxCtCiA81zn20IastZcl9vhBi
aNE9i6/5vcbf7zZ6dqMQ4hEhRKXx+5EQYkPj2gudW/pC/UKI7wgh8kue97PUcfEgvVHeKG+Uf87y
fwGOdMwg8PUgAAAAAABJRU5ErkJggg==
"/> 
   </g> 
</svg>	

	<?php	
}

function icon_location($w, $h){
	?>
		<svg 
		     version="1.1" 
		     xmlns="http://www.w3.org/2000/svg" 
		     xmlns:xlink="http://www.w3.org/1999/xlink" 
		     width="<?=$w?>px" height="<?=$h?>px" 
		     viewBox="0 0 60 107" preserveAspectRatio="none"> 
		   <g> 
		<image width="60" height="107" xlink:href="data:image/png;base64, 
		iVBORw0KGgoAAAANSUhEUgAAADwAAABrCAYAAAArd+E9AAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A
		/wD/oL2nkwAAAAlwSFlzAABS8gAAUvIBT8cvyQAAAAd0SU1FB90FHgAgCm8DxzEAAAHGSURBVHja
		7ZxRloMgEAQzvNz/yu7P7s++mKiZHnugOABSqQYVmcRD0LZt2zL6iYjIHls4girBwxlUAR4dQDPB
		oxNoBnh0hb0KHV1Br4KPx2Itups9axrDne0esRyzwX6Cjhlh30HHrLB70GsvWrPZfWV5XcOz2v1v
		+en0nFvxo4fjToVyPONuq6qdjd2+Fb9m1oAVYxuusCrTwxVW1edy9+HhbFfRN4bd7GZfA8MAAwzw
		esAVr3VZ18AwwAaxzux7uA5M1eeoeCx0aZItnkwjLXY8sgYq28iTX+DklFGPQ74v/QfwCbzqQ8Cz
		asGwOerkOCjltOJJC+DZ4u26uKhuixieyfKrez+LFsArzOEZ5vHeszuGZ7D87s0Mw90tcyKeSB9o
		XWJ9ZP8Mw10tU6gF8MlIO8f6zGY/hrtZPvsph0WLSBvH+srHfAx3sXz1qAaGO1j+5iAOtyUibRbr
		b8+VYdjZcsapQQy7WqaMB+DiSCtjbfefeEpoymkBvjnSmbG2L4lf1nCGZVXxCYYdLCtLi7gtEeni
		WKsr5UrK8I5CV5QFMoeZw0WxrqpyLS2l3YOuLOllDjOHxbGurlBfzvAtbfttd1z7BwOx+KRZ4wiI
		AAAAAElFTkSuQmCC
		"/> 
		   </g> 
		</svg>	
	<?php
}


function icon_magni_glass($w, $h){
	?>
					<svg 
							     version="1.1" 
							     xmlns="http://www.w3.org/2000/svg" 
							     xmlns:xlink="http://www.w3.org/1999/xlink" 
							     width="<?=$w?>px" height="<?=$h?>px" 
							     viewBox="0 0 25 26" preserveAspectRatio="none"> 
							   <g> 
							<image width="25" height="26" xlink:href="data:image/png;base64, 
							iVBORw0KGgoAAAANSUhEUgAAABkAAAAaCAYAAABCfffNAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A
							/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB90FHRcPAw8fXeMAAAH8SURBVEjH
							rZUxa1RREIVnVgkiKoiwxs5SizQa0EYULCSNnSCCghZGC3u1S5MfYCmpRBAb/4AptTFdIFgFrJIt
							FBXdxOzbc47FzsXLIvvue7yB5S27991vzsy5c82yIJmej0h+ILkvSSQl6QvJNQDnzcwAWKuQdDlt
							mn3+pO+TvyiS71qBAFyPjQRgW9KTqQTOkXwdEJDcKgZJMkkLCUByddbLAPokf0oCyU/FKkhWJAXg
							WWFSR0hWoXq5pEz3QsVOg94ZgLuh/HuJivVQ8SC5q0EffwfobF1Wg1ByqKkbSb4IyONZ63pmdtrd
							5e6Nje/uA0nm7v06iEkatjhTJsndvXZtT1JlZsdaqDAzOxmwX3UZrccBe9gUBGAY/bxQt/BOQD6n
							MhSWaylc+bXUJZOhJK2U9CK9E866Xwq5lkAkn85QnZ6KeN/U87ezybsn6cp/IJuYEJgmMoDFRtMY
							QD8yZFaOvVCYshfJVwBeBkwAFpqC5gAs5ptmd8wagPlM/ZtIqCK5SfJW0WjK3TUej11ST1Iv+236
							Fn2bFEX5bra+NWec+ueZaRimuNEpaDQaHSY54L/GJUNcLT1zJa60qqrmSH6bBkm6RNK8K5CZHTWz
							XXc/HpPZJLmki1335wTJYShJivatyyBpkk6RPAjHQdJH6zoCdAbAD5IbZmZ/Ae8G7OJqLfQUAAAA
							AElFTkSuQmCC
							"/> 
							   </g> 
							</svg>	
	
	<?php
}

function icon_arrow_left($w, $h){
	?>
<svg 
     version="1.1" 
     xmlns="http://www.w3.org/2000/svg" 
     xmlns:xlink="http://www.w3.org/1999/xlink" 
      width="<?=$w?>px" height="<?=$h?>px"
     viewBox="0 0 560 560" preserveAspectRatio="none"> 
   <g> 
<image width="560" height="560" xlink:href="data:image/png;base64, 
iVBORw0KGgoAAAANSUhEUgAAAjAAAAIwCAYAAACY8VFvAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A
/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB90FHRcoE8ht/+IAAAtkSURBVHja
7d0xDoMwEABBQPn/l0mTwg2KqPDimQ5wga5aHQXbBgAAAAAAAAAAHefPeO9jLADArOFy9UzAAACZ
cBEwAEAuXAQMAJALFwEDAOTCRcAAALlwETAAQC5cBAwAkAsXAQMA5MJFwAAAuXARMABALlwEDACQ
CxcBAwDkwkXAAAC5cBEwAEAuXAQMAJALFwEDAOTCRcAAALlwETAAQC5cBAwAkAsXAQMAwuWsvruA
AQDhImAAAOEiYAAA4SJgAEC4CBgAQLgIGABAuAgYABAuAgYAEC4CBgAQLgIGAISLgAEAhIuAAQCE
i4ABAOEiYAAA4SJgAADhImAAQLgIGABAuAgYAEC4CBgAEC4IGAAQLgIGABAuAgYAhAsCBgCEi4AB
AOEiXAQMAAgXBAwACBcBAwDCBQEDAMIFAQMAwkXAAIBwQcAAgHBBwACAcBEwACBcEDAAIFwQMAAg
XBAwAAgXBAwACBcEDAAIFwQMAMIFAQMAwgUBAwDCBQEDgHBBwACAcEHAAIBwQcAAIFwQMAAgXBAw
ACBcEDAACBcEDAAIFwQMAAgXBAwAwgUBAwDCBQEDgHARLggYAIQLCBgAhAsCBgDhAgIGAOECAgYA
4YKAAUC4gIABQLiAgAFAuCBgABAuIGAAEC4gYAAQLggYAIQLCBgAhAsIGACECwIGAOECAgYA4QIC
BgDhAgIGQLiAgAFAuICAAUC4gIABEC4gYAAQLiBgABAuIGAAhAsIGACECwgYAIQLCBgA4QICBgDh
AgIGQLiYAggYAOECAgYA4QICBkC4AAIGQLgAAgZAuICAARAugIABEC6AgAEQLiBgAIQLIGAAhAsg
YACECwgYAOECCBgA4QIIGADhAgIGQLgAAgZAuAACBkC4gIABEC6AgAEQLoCAARAuIGAAhAsgYACE
CyBgAIQLIGAA4QIIGADhAggYAOECCBhAuAACBkC4AAIGEC4AAgYQLoCAARAugIABhAuAgAGECyBg
AIQLIGAA4QIgYADhAggYAOECCBhAuAAIGEC4AAgYQLgAAgYQLgACBhAuAAIGEC6AgAGEC4CAAYQL
gIABhAsgYADhAiBgAOECIGAA4QIIGEC4AAgYQLgACBhAuAACBhAuAAIGEC4AAgYQLoCAAYQLgIAB
hAuAgAHhAoCAAeECIGAA4QIgYEC4ACBgQLgACBhAuAAIGBAuAAgYEC4AAgYQLgACBoQLAAIGhAuA
gAGEC4CAAeECgIAB4QIgYADhAiBgQLgAIGBAuAAgYEC4AAgYEC4ACBgQLgAIGBAuAAIGhAsAAgaE
CwACBoQLgIAB4QKAgAHhAoCAAeECIGBAuAAgYEC4ACBgEC4ACBgQLgAIGBAuAAgYhAsACBiECwAC
BoQLAAIG4QIAAgbhAoCAAeECgIBBuACAgEG4ACBgQLgAIGAQLgAgYBAuAAgYEC4ACBiECwAIGIQL
AAIGhAsAAgbhAgACBuECgIAB4QKAgEG4AICAQbgAgIBBuAAgYBAuACBgEC4AIGAQLgAIGIQLAAgY
hAsACBjhAgACBuECAAIG4QIAAka4AICAQbgAgIBBuACAgBEuACBgEC4AIGAQLgAgYIQLACBghAsA
CBiECwAIGOECAAgY4QIAAgbhAgACRrgAAAJGuACAgEG4AICAES4AgIARLgAgYBAuACBghAsAIGCE
CwAIGIQLAAgY4QIACBjhAgACBuECAAJGuAAAAka4AADLBoxwAQABI1wAAAEjXACAZQNGuACAgBEu
AICAES4AwLIBI1wAQMAIFwBAwAgXAGDZgBEuAEAmYIQLAJAJGOECAGQCRrgAAJmAES4AQCZghAsA
kAkY4QIAZAJGuAAAmYARLgBAJmCECwCQCRjhAgBkAka4AACZgBEuAEAmYIQLAJAJGOECAGQCRrgA
AJmAES4AQCZghAsAkAkY4QIAZAJGuAAABcd4se/7biQAwOwug8U2BgCYKlqGRcvfjYuQAQBmC5jj
zmEAgCli5s5h2xgA4LFoufMJScgAAK8IGCEDAGQDRsgAANmAETIAQDZghAwAkA0YIQMAZANGyAAA
2YARMgBANmCEDACQDRghAwBkA0bIAADZgBEyAEA2YIQMAJANGCEDAGQDRsgAANmAETIAQDZghAwA
CJhswAgZABAweUIGAASMkAEABIyQAQAEjJABAAHzdkIGAASMkAEABIyQAQAEjJABAAEjZAAAASNk
AAABI2QAQMAgZABAwAgZAEDACBkAEDAIGQAQMEIGABAwQgYABIyAETIAIGAQMgAgYIQMACBghAwA
CBiEDAAIGCEDAAgYIQMAAgYhAwACBiEDAAJGyACAgEHIAICAQcgAgIARMgAgYBAyACBgEDIAIGAQ
MgAIGAEjZABAwCBkAEDAIGQAQMAIGQAQMAgZABAwCBkAEDAIGQAEDEIGAAQMQgYABAxCBgABg5AB
AAGDkAEAAYOQAUDAgJABQMAgZABAwCBkABAwIGQAEDAIGVMAQMAgZAAQMAIGIQOAgAEhA4CAQcgA
gIBByAAgYEDIACBgQMgAIGAQMgAIGBAyAAgYEDIACBiEDAACBoQMAAIGhAwAAgaEDICAASEDgIAB
IQOAgAEhAyBgBAxCBgABA0IGAAEDQgYAAQNCBkDAgJABQMCAkAFAwICQARAwIGQAEDAgZAAQMCBk
AAQMIGQABAwIGQAEDAgZAAEDCBkAAQNCBgABA0IGQMAYBwgZAAEDCBkAAQNCBgABA0IGQMAAQgZA
wICQAUDAgJABEDCAkAEQMICQARAwIGQABAwgZAAEDCBkAAQMCBkAAQMIGQABAwgZAAEDCBlAwABC
BkDAAEIGQMAAQgYQMAIGhIyQAQQMIGQABAwgZAAEDCBkAAEDCBkAAQMIGQABAwgZQMAACBlAwABC
BkDAAEIGEDAAQgYQMICQARAwgJABBAyAkAEEDICQAQQMIGQAASNgACEDCBgAIQMIGEDIAAgYQMgA
AgZAyAACBkDIAAIGEDKAgAEQMoCAARAygIABhAwgYACEDCBgAIQMIGAAhAwIGAAhAwgYACEDCBgA
IQMCBkDIAAIGQMgAAgZAyICAETAAQgYEDICQAQQMgJABBAyAkAEBAyBkAAEDIGQAAQMgZEDAACBk
QMAACBlAwAAIGRAwAAgZEDAAQgYQMABCBgQMAEIGBAwAQgYEDICQAQEjYACEDAgYAIQMCBgAISNk
QMAACBkQMAAIGRAwAAgZEDAAQgYEDABCBgQMAEIGBAwAQgYBA4CQAQEDgJABAQOAkEHAACBkQMAA
IGRAwAAgZBAwxgGAkEHAACBkQMAAIGRAwAAgZBAwAAgZEDAACBkQMAAIGQQMAAgZBAwAQgYEDABC
BgEDAEIGAQOAkAEBA4CQQcAAgJBBwACAkEHAACBkEDAAIGQQMAAgZBAwAAgZBIyAAUDIIGAAQMgg
YABAyCBgABAyCBgAEDIIGAAQMggYAIQMAgYAhAwCBgCEDAIGAISMgAEAIYOAAQAhg4ABACEjYABA
yCBgAEDIIGAAQMgIGAEDAEJGwACAkEHAAICQQcAAgJARMAAgZISMgAEAIYOAAQAhI2AAACEjYABA
yCBgAEDICBgAQMgIGABAyAgYABAyAgYAEDICBgAQMgIGAISMgAEAhIyAAQCEjIABAJYPGQEDAEJG
wAAAQkbAAABCRsAAgJARMACAkBEwAICQETAAwMtCRsAAgJARMACAkBEwAICQETAAQD1kBAwAkAsZ
AQMA5EJGwAAAuZARMABALmQEDACQCxkBAwDkQkbAAAC5kBEwAEAuZAQMAJALGQEDAORCRsAAALmQ
ETAAQC5kBAwAkAsZAQMA5EJGwAAAuZARMABALmQEDACQCxkBAwDkQmYMGACA6UPmqT9gAwAAAAAA
kPEFpAGph3+ZciUAAAAASUVORK5CYII=
"/> 
   </g> 
</svg>	
	
	<?php
	
}

function icon_arrow_right($w, $h){
	?>
		<svg 
		     version="1.1" 
		     xmlns="http://www.w3.org/2000/svg" 
		     xmlns:xlink="http://www.w3.org/1999/xlink" 
		     width="<?=$w?>px" height="<?=$h?>px"
		     viewBox="0 0 560 560" preserveAspectRatio="none"> 
		   <g> 
		<image width="560" height="560" xlink:href="data:image/png;base64, 
		iVBORw0KGgoAAAANSUhEUgAAAjAAAAIwCAYAAACY8VFvAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A
		/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB90FHRcoI+60z04AAAtgSURBVHja
		7dkxDoJAAEVBduP9r7x2BhNLNTx2piM28qPkAccBAAAAAAAAb8b5YK21Xh+MMcwDAKQCRsgAANmA
		ETIAQDZghAwAkA0YIQMAZANGyAAA2YARMgBANmCEDACQDRghAwBkA0bIAADZgBEyAEA2YIQMAJAN
		GCEDAGQDRsgAANmAETIAQDZghAwAkA0YIQMAZANGyAAA2YARMgBANmCEDACQDRghAwBkA0bIAICA
		yQaMkAEAAbPyJyRkAEDACBkAQMAIGQBAwAgZABAwdz9hIQMAAkbIAAACRsgAAAJGyACAgBEyAICA
		ETIAgIARMgAgYBAyACBghAwAIGCEDAAIGIQMAAgYIQMACBghAwACRsAIGQAQMAgZABAwQgYAEDBC
		BgAEDEIGAASMkAEABIyQAQABg5ABAAGDkAEAASNkAEDAIGQAQMAgZABAwAgZABAwCBkAEDAIGQAQ
		MAgZAASMgBEyACBgEDIAIGAQMgAgYIQMAAgYhAwACBiEDAAIGIQMAAIGIQMAAgYhAwACBiEDgIBB
		yACAgEHIAICAQcgAIGBAyAAgYBAyACBgEDIACBiTIGQAEDAIGQAQMAgZAASMgEHIACBgQMgAIGAQ
		MgAgYBAyAAgYEDIACBgQMgAIGIQMAAIGhAwAAgaEDAACBiEDgIABIQOAgAEhA4CAASEDIGBAyAAg
		YEDIACBgQMgACBgBg5ABQMCAkAFAwICQAUDAgJABEDAgZAAQMCBkABAwIGQABAwIGQAEDAgZAAQM
		CBkAAQMIGQABA0IGAAEDQgZAwABCBkDAgJABQMCAkAHY0TQB/J6bA4Av3xi6yMKf/3SexgAIGBAy
		AAJGwICQARAwgJABEDAgZABcKwUMCBkAAQMIGQABAwgZAAEDQgZAwABCBkDAAEIGQMCAkAEQMICQ
		ARAwgJABEDCAkAEEDCBkAAQMIGQABAwgZAABAwgZAAEDCBkAAQMIGUDACBhAyAACBhAyAAIGEDIA
		AgYQMoCAAYQMgIABhAyAgAGEDCBgAIQMIGAAIQMgYAAhAwgYACEDCBhAyAAIGEDIAAIGQMgAAgZA
		yAACBhAygIARMICQAQQMgJABBAwgZAAEDCBkAAEDIGQAAQMgZAABAwgZQMAACBlAwAAIGUDAAEIG
		EDAAQgYQMABCBhAwAEIGBAyAkAEEDICQAQQMgJABAQOAkAEBAyBkAAEDIGRAwAgYACEDAgZAyAAC
		BkDIAAIGQMiAgAFAyICAARAygIABEDIgYAAQMiBgAIQMIGAAhAwIGACEDAgYAIQMCBgAIQMCBgAh
		AwIGACEDAgZAyICAETAAQgYEDABCBgQMAEIGBAyAkAEBA4CQAQEDgJABAQMgZEDAACBkQMAAIGRA
		wAAgZBAwAAgZEDAACBkQMAAIGQQMAEIGBAwAQgYEDABCBgEjYAAQMggYAIQMCBgAhAx+ewIGACGD
		gAFAyICAAUDIgIABQMggYABAyCBgABAyIGAAEDIIGAAQMggYAISMFRAwAAgZBAwACBkEDAAIGQQM
		AEIGAQMAQgYBAwBCBgEDAEJGwAgYAIQMAgYAhAwCBgCEDAIGACGDgAEAIYOAAQAhg4ABACEjYABA
		yCBgAEDIIGAAQMgIGAAQMggYABAyCBgAEDICBgAQMgIGAIQMAgYAhIyAETAAIGQEDAAIGQQMAAgZ
		BAwACBkBAwAIGQEDAEIGAQMAQkbAAABCRsAAgJBBwACAkBEwAICQETAAgJARMAAgZAQMACBkBAwA
		IGQEDAAIGQEDAAgZAQMACBkBAwDsHTICBgCEjIABAISMgAEAhIyAAQAhI2AAACEjYAAAISNgAICb
		hYyAAQByISNgAIBcyAgYACAXMgIGAMiFjIABAHIhI2AAgFzICBgAIBcyAgYAyIWMgAEAciEjYACA
		XMgIGAAgFzICBgDIhYyAAQByISNgAIBcyAgYACAXMgIGAMiFjIABAHIhI2AAgFzICBgAIBcyAgYA
		yIXMNAcAUPMwAQBwZZ9eIQkYACATLgIGAMiFi4ABAHLhImAAgFy4CBgAIBcuAgYAyIWLgAEAcuEi
		YACAXLgIGAAgFy4CBgDIhYuAAQBy4SJgAIBcuAgYACAXLgIGAMiFi4ABAHLhImAAgFy4CBgAIBcu
		AgYAyIWLgAEAcuEiYACAXLgIGAAQLqP63QUMAAgXAQMACBcBAwAIFwEDAMJFwAAAwkXAAADCRcAA
		gHARMACAcBEwAIBwETAAIFwEDAAgXAQMACBcBAwACBcBAwAIFwEDAAgXAQMAwkXAAADCRcAAAMJF
		wACAcEHAAIBwETAAgHARMAAgXBAwACBcBAwACBfhImAAQLggYABAuAgYABAuCBgAEC4IGAAQLgIG
		AIQLAgYAhAsCBgCEi4ABAOGCgAEA4YKAAQDhgoABQLggYABAuCBgAEC4IGAAEC4IGAAQLggYABAu
		CBgAhAsCBgCECwIGAIQLAgYA4YKAAQDhgoABAOGCgAFAuCBgAEC4IGAAQLggYAAQLggYABAuCBgA
		hItwQcAAIFxAwAAgXBAwAAgXEDAACBcQMAAIFwQMAMIFBAwAwgUEDADCBQEDgHABAQOAcAEBA4Bw
		QcAAIFxAwAAgXEDAACBcEDAACBcQMAAIFxAwAAgXEDAAwgUEDADCBQQMAMIFBAyAcAEBA4BwAQED
		gHABAQMgXEDAACBcQMAAIFxAwAAIFxAwAAgXEDAAwsUKIGAAhAsIGACECwgYAOECCBgA4QIIGADh
		AgIGQLgAAgZAuAACBkC4gIABEC6AgAEQLoCAARAuIGAAhAsgYACECyBgAIQLCBgA4QIIGADhAggY
		AOECAgZAuAACBkC4AAIGQLiAgAEQLoCAARAugIABEC6AgAGECyBgAIQLIGAAhAsgYADhAggYAOEC
		CBhAuAAIGEC4AAIGQLgAAgYQLgACBhAugIABEC6AgAGEC4CAAYQLIGAAhAsgYADhAiBgAOECIGAA
		4QIIGEC4AAgYQLgACBhAuAACBhAuAAIGEC4AAgYQLoCAAYQLgIABhAuAgAGECyBgAOECIGAA4QIg
		YADhAggYQLgACBhAuAAIGEC4AAIGEC4AAgYQLgACBoQLAAIGhAuAgAGEC4CAAeECgIAB4QIgYADh
		AiBgQLgAIGBAuAAIGEC4AAgYEC4ACBgQLgACBhAuAJc1TQDiBaDGExgQLgACBoQLAAIGhAsAAgaE
		C4CAAeECgIAB4QKAgAHhAiBgQLgAIGBAuAAgYEC4AAgYEC4ACBgQLgAIGBAuAAIGhAsAAgaECwAC
		BoQLgIAB4QKAgAHhAoCAAeECgIBBuAAgYEC4ACBgEC5WAEDAIFwAEDAgXAAQMAgXABAwCBcABAwI
		FwAEDMIFAAQMwgUAAQPCBQABg3ABAAGDcAFAwIBwAUDAIFwAQMAgXABAwCBcABAwCBcAEDAIFwAQ
		MAgXAAQMwgUABAzCBQAEDMIFAAGDcAEAAYNwAQABg3ABQMAgXABAwCBcAEDAIFwAEDAIFwAQMAgX
		ABAwwgUABAzCBQAEDMIFAASMcAEABIxwAQABg3ABAAEjXAAAASNcAEDAIFwAQMAIFwBAwAgXABAw
		CBcAEDDCBQAQMMIFAAQMwgUABIxwAQAEjHABAAGDcAEAASNcAAABI1wAAAEjXABAwAgXAEDACBcA
		QMAIFwAQMMIFABAwwgUAEDDCBQAEjHABAASMcAEAdg4Y4QIAAka4AAACRrgAANsGjHABADIBI1wA
		gEzACBcAIBMwwgUAyASMcAEAMgEjXACATMAIFwAgEzDCBQDIBIxwAQAyASNcAIBMwAgXACATMMIF
		AMgEjHABADIBI1wAgEzACBcAIBMwwgUAyASMcAEAMgEjXACATMAIFwAgEzDCBQAAAAAAAACAiCeZ
		9F3vVkciZAAAAABJRU5ErkJggg==
		"/> 
		   </g> 
		</svg>	
<?php
	
}


function get_domain() {
	$CI = & get_instance();
	$bar_url_pieces = explode('.', $CI->config->item('base_url'));
	$domanin = str_replace(array (
		'http://',
		'https://'
	), '', strtolower($bar_url_pieces[0]));
	return $domanin;
}

function get_user_config() {
	$CI = & get_instance();
	return $CI->session->userdata('user_config');
}

function check_feature($feature) {

	$user_config = get_user_config();

	return in_array($feature, $user_config['features']);
}