<?php
if (!defined('BASEPATH'))
	exit ('No direct script access allowed');

function get_config_val($key) {
	$CI = & get_instance();
	return $CI->config_model->get_value($key);
}

function ci_config($key) {
	$CI = & get_instance();
	return $CI->config->item($key);
}

function get_hash() {
	$uniq = uniqid('', TRUE);
	return md5($uniq);
}

function current_lang(){
	$CI = & get_instance();
	return $CI->lang->lang();
	
}


function icon_location($w, $h){
	?>
		<svg 
		     version="1.1" 
		     xmlns="http://www.w3.org/2000/svg" 
		     xmlns:xlink="http://www.w3.org/1999/xlink" 
		     width="<?=$w?>px" height="<?=$h?>px" 
		     viewBox="0 0 60 107" preserveAspectRatio="none"> 
		   <g> 
		<image width="60" height="107" xlink:href="data:image/png;base64, 
		iVBORw0KGgoAAAANSUhEUgAAADwAAABrCAYAAAArd+E9AAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A
		/wD/oL2nkwAAAAlwSFlzAABS8gAAUvIBT8cvyQAAAAd0SU1FB90FHgAgCm8DxzEAAAHGSURBVHja
		7ZxRloMgEAQzvNz/yu7P7s++mKiZHnugOABSqQYVmcRD0LZt2zL6iYjIHls4girBwxlUAR4dQDPB
		oxNoBnh0hb0KHV1Br4KPx2Itups9axrDne0esRyzwX6Cjhlh30HHrLB70GsvWrPZfWV5XcOz2v1v
		+en0nFvxo4fjToVyPONuq6qdjd2+Fb9m1oAVYxuusCrTwxVW1edy9+HhbFfRN4bd7GZfA8MAAwzw
		esAVr3VZ18AwwAaxzux7uA5M1eeoeCx0aZItnkwjLXY8sgYq28iTX+DklFGPQ74v/QfwCbzqQ8Cz
		asGwOerkOCjltOJJC+DZ4u26uKhuixieyfKrez+LFsArzOEZ5vHeszuGZ7D87s0Mw90tcyKeSB9o
		XWJ9ZP8Mw10tU6gF8MlIO8f6zGY/hrtZPvsph0WLSBvH+srHfAx3sXz1qAaGO1j+5iAOtyUibRbr
		b8+VYdjZcsapQQy7WqaMB+DiSCtjbfefeEpoymkBvjnSmbG2L4lf1nCGZVXxCYYdLCtLi7gtEeni
		WKsr5UrK8I5CV5QFMoeZw0WxrqpyLS2l3YOuLOllDjOHxbGurlBfzvAtbfttd1z7BwOx+KRZ4wiI
		AAAAAElFTkSuQmCC
		"/> 
		   </g> 
		</svg>	
	<?php
}


function icon_magni_glass($w, $h){
	?>
							<svg 
							     version="1.1" 
							     xmlns="http://www.w3.org/2000/svg" 
							     xmlns:xlink="http://www.w3.org/1999/xlink" 
							     width="<?=$w?>px" height="<?=$h?>px" 
							     viewBox="0 0 25 26" preserveAspectRatio="none"> 
							   <g> 
							<image width="25" height="26" xlink:href="data:image/png;base64, 
							iVBORw0KGgoAAAANSUhEUgAAABkAAAAaCAYAAABCfffNAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A
							/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB90FHRcPAw8fXeMAAAH8SURBVEjH
							rZUxa1RREIVnVgkiKoiwxs5SizQa0EYULCSNnSCCghZGC3u1S5MfYCmpRBAb/4AptTFdIFgFrJIt
							FBXdxOzbc47FzsXLIvvue7yB5S27991vzsy5c82yIJmej0h+ILkvSSQl6QvJNQDnzcwAWKuQdDlt
							mn3+pO+TvyiS71qBAFyPjQRgW9KTqQTOkXwdEJDcKgZJMkkLCUByddbLAPokf0oCyU/FKkhWJAXg
							WWFSR0hWoXq5pEz3QsVOg94ZgLuh/HuJivVQ8SC5q0EffwfobF1Wg1ByqKkbSb4IyONZ63pmdtrd
							5e6Nje/uA0nm7v06iEkatjhTJsndvXZtT1JlZsdaqDAzOxmwX3UZrccBe9gUBGAY/bxQt/BOQD6n
							MhSWaylc+bXUJZOhJK2U9CK9E866Xwq5lkAkn85QnZ6KeN/U87ezybsn6cp/IJuYEJgmMoDFRtMY
							QD8yZFaOvVCYshfJVwBeBkwAFpqC5gAs5ptmd8wagPlM/ZtIqCK5SfJW0WjK3TUej11ST1Iv+236
							Fn2bFEX5bra+NWec+ueZaRimuNEpaDQaHSY54L/GJUNcLT1zJa60qqrmSH6bBkm6RNK8K5CZHTWz
							XXc/HpPZJLmki1335wTJYShJivatyyBpkk6RPAjHQdJH6zoCdAbAD5IbZmZ/Ae8G7OJqLfQUAAAA
							AElFTkSuQmCC
							"/> 
							   </g> 
							</svg>	
	
	<?php
}

function icon_arrow_left($w, $h){
	?>
<svg 
     version="1.1" 
     xmlns="http://www.w3.org/2000/svg" 
     xmlns:xlink="http://www.w3.org/1999/xlink" 
      width="<?=$w?>px" height="<?=$h?>px"
     viewBox="0 0 560 560" preserveAspectRatio="none"> 
   <g> 
<image width="560" height="560" xlink:href="data:image/png;base64, 
iVBORw0KGgoAAAANSUhEUgAAAjAAAAIwCAYAAACY8VFvAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A
/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB90FHRcoE8ht/+IAAAtkSURBVHja
7d0xDoMwEABBQPn/l0mTwg2KqPDimQ5wga5aHQXbBgAAAAAAAAAAHefPeO9jLADArOFy9UzAAACZ
cBEwAEAuXAQMAJALFwEDAOTCRcAAALlwETAAQC5cBAwAkAsXAQMA5MJFwAAAuXARMABALlwEDACQ
CxcBAwDkwkXAAAC5cBEwAEAuXAQMAJALFwEDAOTCRcAAALlwETAAQC5cBAwAkAsXAQMAwuWsvruA
AQDhImAAAOEiYAAA4SJgAEC4CBgAQLgIGABAuAgYABAuAgYAEC4CBgAQLgIGAISLgAEAhIuAAQCE
i4ABAOEiYAAA4SJgAADhImAAQLgIGABAuAgYAEC4CBgAEC4IGAAQLgIGABAuAgYAhAsCBgCEi4AB
AOEiXAQMAAgXBAwACBcBAwDCBQEDAMIFAQMAwkXAAIBwQcAAgHBBwACAcBEwACBcEDAAIFwQMAAg
XBAwAAgXBAwACBcEDAAIFwQMAMIFAQMAwgUBAwDCBQEDgHBBwACAcEHAAIBwQcAAIFwQMAAgXBAw
ACBcEDAACBcEDAAIFwQMAAgXBAwAwgUBAwDCBQEDgHARLggYAIQLCBgAhAsCBgDhAgIGAOECAgYA
4YKAAUC4gIABQLiAgAFAuCBgABAuIGAAEC4gYAAQLggYAIQLCBgAhAsIGACECwIGAOECAgYA4QIC
BgDhAgIGQLiAgAFAuICAAUC4gIABEC4gYAAQLiBgABAuIGAAhAsIGACECwgYAIQLCBgA4QICBgDh
AgIGQLiYAggYAOECAgYA4QICBkC4AAIGQLgAAgZAuICAARAugIABEC6AgAEQLiBgAIQLIGAAhAsg
YACECwgYAOECCBgA4QIIGADhAgIGQLgAAgZAuAACBkC4gIABEC6AgAEQLoCAARAuIGAAhAsgYACE
CyBgAIQLIGAA4QIIGADhAggYAOECCBhAuAACBkC4AAIGEC4AAgYQLoCAARAugIABhAuAgAGECyBg
AIQLIGAA4QIgYADhAggYAOECCBhAuAAIGEC4AAgYQLgAAgYQLgACBhAuAAIGEC6AgAGEC4CAAYQL
gIABhAsgYADhAiBgAOECIGAA4QIIGEC4AAgYQLgACBhAuAACBhAuAAIGEC4AAgYQLoCAAYQLgIAB
hAuAgAHhAoCAAeECIGAA4QIgYEC4ACBgQLgACBhAuAAIGBAuAAgYEC4AAgYQLgACBoQLAAIGhAuA
gAGEC4CAAeECgIAB4QIgYADhAiBgQLgAIGBAuAAgYEC4AAgYEC4ACBgQLgAIGBAuAAIGhAsAAgaE
CwACBoQLgIAB4QKAgAHhAoCAAeECIGBAuAAgYEC4ACBgEC4ACBgQLgAIGBAuAAgYhAsACBiECwAC
BoQLAAIG4QIAAgbhAoCAAeECgIBBuACAgEG4ACBgQLgAIGAQLgAgYBAuAAgYEC4ACBiECwAIGIQL
AAIGhAsAAgbhAgACBuECgIAB4QKAgEG4AICAQbgAgIBBuAAgYBAuACBgEC4AIGAQLgAIGIQLAAgY
hAsACBjhAgACBuECAAIG4QIAAka4AICAQbgAgIBBuACAgBEuACBgEC4AIGAQLgAgYIQLACBghAsA
CBiECwAIGOECAAgY4QIAAgbhAgACRrgAAAJGuACAgEG4AICAES4AgIARLgAgYBAuACBghAsAIGCE
CwAIGIQLAAgY4QIACBjhAgACBuECAAJGuAAAAka4AADLBoxwAQABI1wAAAEjXACAZQNGuACAgBEu
AICAES4AwLIBI1wAQMAIFwBAwAgXAGDZgBEuAEAmYIQLAJAJGOECAGQCRrgAAJmAES4AQCZghAsA
kAkY4QIAZAJGuAAAmYARLgBAJmCECwCQCRjhAgBkAka4AACZgBEuAEAmYIQLAJAJGOECAGQCRrgA
AJmAES4AQCZghAsAkAkY4QIAZAJGuAAABcd4se/7biQAwOwug8U2BgCYKlqGRcvfjYuQAQBmC5jj
zmEAgCli5s5h2xgA4LFoufMJScgAAK8IGCEDAGQDRsgAANmAETIAQDZghAwAkA0YIQMAZANGyAAA
2YARMgBANmCEDACQDRghAwBkA0bIAADZgBEyAEA2YIQMAJANGCEDAGQDRsgAANmAETIAQDZghAwA
CJhswAgZABAweUIGAASMkAEABIyQAQAEjJABAAHzdkIGAASMkAEABIyQAQAEjJABAAEjZAAAASNk
AAABI2QAQMAgZABAwAgZAEDACBkAEDAIGQAQMEIGABAwQgYABIyAETIAIGAQMgAgYIQMACBghAwA
CBiEDAAIGCEDAAgYIQMAAgYhAwACBiEDAAJGyACAgEHIAICAQcgAgIARMgAgYBAyACBgEDIAIGAQ
MgAIGAEjZABAwCBkAEDAIGQAQMAIGQAQMAgZABAwCBkAEDAIGQAEDEIGAAQMQgYABAxCBgABg5AB
AAGDkAEAAYOQAUDAgJABQMAgZABAwCBkABAwIGQAEDAIGVMAQMAgZAAQMAIGIQOAgAEhA4CAQcgA
gIBByAAgYEDIACBgQMgAIGAQMgAIGBAyAAgYEDIACBiEDAACBoQMAAIGhAwAAgaEDICAASEDgIAB
IQOAgAEhAyBgBAxCBgABA0IGAAEDQgYAAQNCBkDAgJABQMCAkAFAwICQARAwIGQAEDAgZAAQMCBk
AAQMIGQABAwIGQAEDAgZAAEDCBkAAQNCBgABA0IGQMAYBwgZAAEDCBkAAQNCBgABA0IGQMAAQgZA
wICQAUDAgJABEDCAkAEQMICQARAwIGQABAwgZAAEDCBkAAQMCBkAAQMIGQABAwgZAAEDCBlAwABC
BkDAAEIGQMAAQgYQMAIGhIyQAQQMIGQABAwgZAAEDCBkAAEDCBkAAQMIGQABAwgZQMAACBlAwABC
BkDAAEIGEDAAQgYQMICQARAwgJABBAyAkAEEDICQAQQMIGQAASNgACEDCBgAIQMIGEDIAAgYQMgA
AgZAyAACBkDIAAIGEDKAgAEQMoCAARAygIABhAwgYACEDCBgAIQMIGAAhAwIGAAhAwgYACEDCBgA
IQMCBkDIAAIGQMgAAgZAyICAETAAQgYEDICQAQQMgJABBAyAkAEBAyBkAAEDIGQAAQMgZEDAACBk
QMAACBlAwAAIGRAwAAgZEDAAQgYQMABCBgQMAEIGBAwAQgYEDICQAQEjYACEDAgYAIQMCBgAISNk
QMAACBkQMAAIGRAwAAgZEDAAQgYEDABCBgQMAEIGBAwAQgYBA4CQAQEDgJABAQOAkEHAACBkQMAA
IGRAwAAgZBAwxgGAkEHAACBkQMAAIGRAwAAgZBAwAAgZEDAACBkQMAAIGQQMAAgZBAwAQgYEDABC
BgEDAEIGAQOAkAEBA4CQQcAAgJBBwACAkEHAACBkEDAAIGQQMAAgZBAwAAgZBIyAAUDIIGAAQMgg
YABAyCBgABAyCBgAEDIIGAAQMggYAIQMAgYAhAwCBgCEDAIGAISMgAEAIYOAAQAhg4ABACEjYABA
yCBgAEDIIGAAQMgIGAEDAEJGwACAkEHAAICQQcAAgJARMAAgZISMgAEAIYOAAQAhI2AAACEjYABA
yCBgAEDICBgAQMgIGABAyAgYABAyAgYAEDICBgAQMgIGAISMgAEAhIyAAQCEjIABAJYPGQEDAEJG
wAAAQkbAAABCRsAAgJARMACAkBEwAICQETAAwMtCRsAAgJARMACAkBEwAICQETAAQD1kBAwAkAsZ
AQMA5EJGwAAAuZARMABALmQEDACQCxkBAwDkQkbAAAC5kBEwAEAuZAQMAJALGQEDAORCRsAAALmQ
ETAAQC5kBAwAkAsZAQMA5EJGwAAAuZARMABALmQEDACQCxkBAwDkQmYMGACA6UPmqT9gAwAAAAAA
kPEFpAGph3+ZciUAAAAASUVORK5CYII=
"/> 
   </g> 
</svg>	
	
	<?php
	
}

function icon_arrow_right($w, $h){
	?>
		<svg 
		     version="1.1" 
		     xmlns="http://www.w3.org/2000/svg" 
		     xmlns:xlink="http://www.w3.org/1999/xlink" 
		     width="<?=$w?>px" height="<?=$h?>px"
		     viewBox="0 0 560 560" preserveAspectRatio="none"> 
		   <g> 
		<image width="560" height="560" xlink:href="data:image/png;base64, 
		iVBORw0KGgoAAAANSUhEUgAAAjAAAAIwCAYAAACY8VFvAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A
		/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB90FHRcoI+60z04AAAtgSURBVHja
		7dkxDoJAAEVBduP9r7x2BhNLNTx2piM28qPkAccBAAAAAAAAb8b5YK21Xh+MMcwDAKQCRsgAANmA
		ETIAQDZghAwAkA0YIQMAZANGyAAA2YARMgBANmCEDACQDRghAwBkA0bIAADZgBEyAEA2YIQMAJAN
		GCEDAGQDRsgAANmAETIAQDZghAwAkA0YIQMAZANGyAAA2YARMgBANmCEDACQDRghAwBkA0bIAICA
		yQaMkAEAAbPyJyRkAEDACBkAQMAIGQBAwAgZABAwdz9hIQMAAkbIAAACRsgAAAJGyACAgBEyAICA
		ETIAgIARMgAgYBAyACBghAwAIGCEDAAIGIQMAAgYIQMACBghAwACRsAIGQAQMAgZABAwQgYAEDBC
		BgAEDEIGAASMkAEABIyQAQABg5ABAAGDkAEAASNkAEDAIGQAQMAgZABAwAgZABAwCBkAEDAIGQAQ
		MAgZAASMgBEyACBgEDIAIGAQMgAgYIQMAAgYhAwACBiEDAAIGIQMAAIGIQMAAgYhAwACBiEDgIBB
		yACAgEHIAICAQcgAIGBAyAAgYBAyACBgEDIACBiTIGQAEDAIGQAQMAgZAASMgEHIACBgQMgAIGAQ
		MgAgYBAyAAgYEDIACBgQMgAIGIQMAAIGhAwAAgaEDAACBiEDgIABIQOAgAEhA4CAASEDIGBAyAAg
		YEDIACBgQMgACBgBg5ABQMCAkAFAwICQAUDAgJABEDAgZAAQMCBkABAwIGQABAwIGQAEDAgZAAQM
		CBkAAQMIGQABA0IGAAEDQgZAwABCBkDAgJABQMCAkAHY0TQB/J6bA4Av3xi6yMKf/3SexgAIGBAy
		AAJGwICQARAwgJABEDAgZABcKwUMCBkAAQMIGQABAwgZAAEDQgZAwABCBkDAAEIGQMCAkAEQMICQ
		ARAwgJABEDCAkAEEDCBkAAQMIGQABAwgZAABAwgZAAEDCBkAAQMIGUDACBhAyAACBhAyAAIGEDIA
		AgYQMoCAAYQMgIABhAyAgAGEDCBgAIQMIGAAIQMgYAAhAwgYACEDCBhAyAAIGEDIAAIGQMgAAgZA
		yAACBhAygIARMICQAQQMgJABBAwgZAAEDCBkAAEDIGQAAQMgZAABAwgZQMAACBlAwAAIGUDAAEIG
		EDAAQgYQMABCBhAwAEIGBAyAkAEEDICQAQQMgJABAQOAkAEBAyBkAAEDIGRAwAgYACEDAgZAyAAC
		BkDIAAIGQMiAgAFAyICAARAygIABEDIgYAAQMiBgAIQMIGAAhAwIGACEDAgYAIQMCBgAIQMCBgAh
		AwIGACEDAgZAyICAETAAQgYEDABCBgQMAEIGBAyAkAEBA4CQAQEDgJABAQMgZEDAACBkQMAAIGRA
		wAAgZBAwAAgZEDAACBkQMAAIGQQMAEIGBAwAQgYEDABCBgEjYAAQMggYAIQMCBgAhAx+ewIGACGD
		gAFAyICAAUDIgIABQMggYABAyCBgABAyIGAAEDIIGAAQMggYAISMFRAwAAgZBAwACBkEDAAIGQQM
		AEIGAQMAQgYBAwBCBgEDAEJGwAgYAIQMAgYAhAwCBgCEDAIGACGDgAEAIYOAAQAhg4ABACEjYABA
		yCBgAEDIIGAAQMgIGAAQMggYABAyCBgAEDICBgAQMgIGAIQMAgYAhIyAETAAIGQEDAAIGQQMAAgZ
		BAwACBkBAwAIGQEDAEIGAQMAQkbAAABCRsAAgJBBwACAkBEwAICQETAAgJARMAAgZAQMACBkBAwA
		IGQEDAAIGQEDAAgZAQMACBkBAwDsHTICBgCEjIABAISMgAEAhIyAAQAhI2AAACEjYAAAISNgAICb
		hYyAAQByISNgAIBcyAgYACAXMgIGAMiFjIABAHIhI2AAgFzICBgAIBcyAgYAyIWMgAEAciEjYACA
		XMgIGAAgFzICBgDIhYyAAQByISNgAIBcyAgYACAXMgIGAMiFjIABAHIhI2AAgFzICBgAIBcyAgYA
		yIXMNAcAUPMwAQBwZZ9eIQkYACATLgIGAMiFi4ABAHLhImAAgFy4CBgAIBcuAgYAyIWLgAEAcuEi
		YACAXLgIGAAgFy4CBgDIhYuAAQBy4SJgAIBcuAgYACAXLgIGAMiFi4ABAHLhImAAgFy4CBgAIBcu
		AgYAyIWLgAEAcuEiYACAXLgIGAAQLqP63QUMAAgXAQMACBcBAwAIFwEDAMJFwAAAwkXAAADCRcAA
		gHARMACAcBEwAIBwETAAIFwEDAAgXAQMACBcBAwACBcBAwAIFwEDAAgXAQMAwkXAAADCRcAAAMJF
		wACAcEHAAIBwETAAgHARMAAgXBAwACBcBAwACBfhImAAQLggYABAuAgYABAuCBgAEC4IGAAQLgIG
		AIQLAgYAhAsCBgCEi4ABAOGCgAEA4YKAAQDhgoABQLggYABAuCBgAEC4IGAAEC4IGAAQLggYABAu
		CBgAhAsCBgCECwIGAIQLAgYA4YKAAQDhgoABAOGCgAFAuCBgAEC4IGAAQLggYAAQLggYABAuCBgA
		hItwQcAAIFxAwAAgXBAwAAgXEDAACBcQMAAIFwQMAMIFBAwAwgUEDADCBQEDgHABAQOAcAEBA4Bw
		QcAAIFxAwAAgXEDAACBcEDAACBcQMAAIFxAwAAgXEDAAwgUEDADCBQQMAMIFBAyAcAEBA4BwAQED
		gHABAQMgXEDAACBcQMAAIFxAwAAIFxAwAAgXEDAAwsUKIGAAhAsIGACECwgYAOECCBgA4QIIGADh
		AgIGQLgAAgZAuAACBkC4gIABEC6AgAEQLoCAARAuIGAAhAsgYACECyBgAIQLCBgA4QIIGADhAggY
		AOECAgZAuAACBkC4AAIGQLiAgAEQLoCAARAugIABEC6AgAGECyBgAIQLIGAAhAsgYADhAggYAOEC
		CBhAuAAIGEC4AAIGQLgAAgYQLgACBhAugIABEC6AgAGEC4CAAYQLIGAAhAsgYADhAiBgAOECIGAA
		4QIIGEC4AAgYQLgACBhAuAACBhAuAAIGEC4AAgYQLoCAAYQLgIABhAuAgAGECyBgAOECIGAA4QIg
		YADhAggYQLgACBhAuAAIGEC4AAIGEC4AAgYQLgACBoQLAAIGhAuAgAGEC4CAAeECgIAB4QIgYADh
		AiBgQLgAIGBAuAAIGEC4AAgYEC4ACBgQLgACBhAuAJc1TQDiBaDGExgQLgACBoQLAAIGhAsAAgaE
		C4CAAeECgIAB4QKAgAHhAiBgQLgAIGBAuAAgYEC4AAgYEC4ACBgQLgAIGBAuAAIGhAsAAgaECwAC
		BoQLgIAB4QKAgAHhAoCAAeECgIBBuAAgYEC4ACBgEC5WAEDAIFwAEDAgXAAQMAgXABAwCBcABAwI
		FwAEDMIFAAQMwgUAAQPCBQABg3ABAAGDcAFAwIBwAUDAIFwAQMAgXABAwCBcABAwCBcAEDAIFwAQ
		MAgXAAQMwgUABAzCBQAEDMIFAAGDcAEAAYNwAQABg3ABQMAgXABAwCBcAEDAIFwAEDAIFwAQMAgX
		ABAwwgUABAzCBQAEDMIFAASMcAEABIxwAQABg3ABAAEjXAAAASNcAEDAIFwAQMAIFwBAwAgXABAw
		CBcAEDDCBQAQMMIFAAQMwgUABIxwAQAEjHABAAGDcAEAASNcAAABI1wAAAEjXABAwAgXAEDACBcA
		QMAIFwAQMMIFABAwwgUAEDDCBQAEjHABAASMcAEAdg4Y4QIAAka4AAACRrgAANsGjHABADIBI1wA
		gEzACBcAIBMwwgUAyASMcAEAMgEjXACATMAIFwAgEzDCBQDIBIxwAQAyASNcAIBMwAgXACATMMIF
		AMgEjHABADIBI1wAgEzACBcAIBMwwgUAyASMcAEAMgEjXACATMAIFwAgEzDCBQAAAAAAAACAiCeZ
		9F3vVkciZAAAAABJRU5ErkJggg==
		"/> 
		   </g> 
		</svg>	
<?php
	
}


function get_domain() {
	$CI = & get_instance();
	$bar_url_pieces = explode('.', $CI->config->item('base_url'));
	$domanin = str_replace(array (
		'http://',
		'https://'
	), '', strtolower($bar_url_pieces[0]));
	return $domanin;
}

function get_user_config() {
	$CI = & get_instance();
	return $CI->session->userdata('user_config');
}

function check_feature($feature) {

	$user_config = get_user_config();

	return in_array($feature, $user_config['features']);
}